version: "3"

services:
  app:
    build:
      context: .
      args:
        - ENV=dev
    container_name: app_dev
    restart: on-failure
    volumes:
      - $HOME/.aws:/root/.aws:ro
      - ./app:/app/app
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - DB_HOST=database
      - DATABASE=geostore
      - DB_USER=gfw
      - DB_PASSWORD=postgres  # pragma: allowlist secret
      - DB_PORT=5432
      - DB_HOST_RO=database
      - DATABASE_RO=geostore
      - DB_USER_RO=gfw_readonly
      - DB_PASSWORD_RO=readonly  # pragma: allowlist secret
      - DB_PORT_RO=5432
      - AWS_DEFAULT_PROFILE=gfw-dev
      - LOG_LEVEL=debug
      - POSTGRESQL_CLIENT_JOB_DEFINITION=postgres_client_jd
      - GDAL_PYTHON_JOB_DEFINITION=gdal_python_jd
      - TILE_CACHE_JOB_DEFINITION=tile_cache_jd
      - PIXETL_JOB_DEFINITION=pixetl_jd
      - AURORA_JOB_QUEUE=aurora_jq
      - AURORA_JOB_QUEUE_FAST=aurora_fast_jq
      - DATA_LAKE_JOB_QUEUE=data_lake_jq
      - TILE_CACHE_JOB_QUEUE=tile_cache_jq
      - PIXETL_JOB_QUEUE=pixetl_jq
      - RASTER_ANALYSIS_LAMBDA_NAME=raster_analysis
      - API_URL="http://app_dev:80"
      - RW_API_URL=https://api.resourcewatch.org
      - GOOGLE_APPLICATION_CREDENTIALS=/root/.gcs/private_key.json
    ports:
      - 8000:80
    entrypoint: wait_for_postgres.sh /start.sh
    depends_on:
      - database

  database:
    container_name: gfw-data-api-database
    image: postgis/postgis:12-2.5-alpine
    restart: on-failure
    ports:
      - 54320:5432
    environment:
      - POSTGRES_DB=geostore
      - POSTGRES_USER=gfw
      - POSTGRES_PASSWORD=postgres  # pragma: allowlist secret
    volumes:
      - database_data:/var/lib/postgresql/data

volumes:
  database_data:
