"""Empty message.

Revision ID: 1082340f8ce1
Revises: 3e524ef0525f
Create Date: 2025-02-11 15:38:36.460512
"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1082340f8ce1"  # pragma: allowlist secret
down_revision = "3e524ef0525f"  # pragma: allowlist secret
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("geostore", sa.Column("info", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("geostore", "info")
    # ### end Alembic commands ###
