"""empty message.

Revision ID: 14384c361a49
Revises: 4763f4b8141a
Create Date: 2021-09-22 17:05:26.698700
"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "14384c361a49"  # pragma: allowlist secret
down_revision = "4763f4b8141a"  # pragma: allowlist secret
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "versions",
        sa.Column("history", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("versions", "history")
    # ### end Alembic commands ###
