"""empty message.

Revision ID: 15a427d4fa82
Revises: a51077c7ffd9
Create Date: 2020-05-22 02:07:22.025251
"""
import geoalchemy2
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "15a427d4fa82"  # pragma: allowlist secret
down_revision = "a51077c7ffd9"  # pragma: allowlist secret
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("geostore", sa.Column("gfw_geojson", sa.String(), nullable=True))
    op.alter_column(
        "geostore", "gfw_area__ha", existing_type=sa.NUMERIC(), nullable=True
    )
    op.alter_column(
        "geostore",
        "gfw_bbox",
        existing_type=geoalchemy2.types.Geometry(
            geometry_type="POLYGON",
            srid=4326,
            from_text="ST_GeomFromEWKT",
            name="geometry",
        ),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "geostore",
        "gfw_bbox",
        existing_type=geoalchemy2.types.Geometry(
            geometry_type="POLYGON",
            srid=4326,
            from_text="ST_GeomFromEWKT",
            name="geometry",
        ),
        nullable=False,
    )
    op.alter_column(
        "geostore", "gfw_area__ha", existing_type=sa.NUMERIC(), nullable=False
    )
    # op.drop_column('geostore', 'gfw_geojson')
    # ### end Alembic commands ###
