"""empty message.

Revision ID: 167eebbf29e4
Revises: cc4ea038ab7b
Create Date: 2020-12-29 15:51:07.973296
"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "167eebbf29e4"  # pragma: allowlist secret
down_revision = "cc4ea038ab7b"  # pragma: allowlist secret
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "assets",
        "extent",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
        existing_server_default=sa.text("'{}'::jsonb"),
        server_default=None,
    )
    op.alter_column(
        "assets",
        "stats",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
        existing_server_default=sa.text("'{}'::jsonb"),
        server_default=None,
    )
    # ### end Alembic commands ###

    assets = sa.sql.table("assets", sa.Column("extent"))
    op.execute(
        assets.update()
        .where(assets.c.extent == sa.text("'{}'::jsonb"))
        .values(extent=None)
    )
    stats = sa.sql.table("assets", sa.Column("stats"))
    op.execute(
        stats.update().where(stats.c.stats == sa.text("'{}'::jsonb")).values(stats=None)
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "assets",
        "stats",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.alter_column(
        "assets",
        "extent",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    # ### end Alembic commands ###
