"""Update empty fields of dynamic vector tile cache.

Revision ID: 19a2413be4d8
Revises: 64e9b1741386
Create Date: 2020-11-12 01:07:16.321395
"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "19a2413be4d8"  # pragma: allowlist secret
down_revision = "64e9b1741386"  # pragma: allowlist secret
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
    UPDATE assets
        SET    fields = default_assets.fields
        FROM   (SELECT DISTINCT dataset,
                                version,
                                fields
                FROM   assets
                WHERE  is_default = true) AS default_assets
        WHERE  assets.dataset = default_assets.dataset
               AND assets.version = default_assets.version
               AND assets.fields = '[]' :: jsonb
               AND assets.asset_type = 'Dynamic vector tile cache' """
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
