"""empty message

Revision ID: 252af4e403c5
Revises: c1100a23a083
Create Date: 2020-06-02 02:52:17.927668

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "252af4e403c5"  # pragma: allowlist secret
down_revision = "15a427d4fa82"  # pragma: allowlist secret
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        CREATE FUNCTION  reset_latest()
        RETURNS trigger LANGUAGE plpgsql AS
        $$
        BEGIN
            IF NEW.is_latest = true THEN

                    UPDATE versions
                       SET is_latest = false
                     WHERE versions.dataset = NEW.dataset;
            END IF;

        RETURN NEW;
        END;
       $$
        """
    )

    op.execute(
        """
    CREATE TRIGGER latest_version
        BEFORE INSERT OR UPDATE ON public.versions
        FOR EACH ROW
        EXECUTE PROCEDURE reset_latest();
    """
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""DROP TRIGGER IF EXISTS latest_version ON public.versions;""")
    op.execute("""DROP FUNCTION reset_latest();""")
    # ### end Alembic commands ###
