"""create userareas table.

Revision ID: 3593e241c4b8
Revises: 12a4acb31f39
Create Date: 2020-07-15 20:25:01.984269
"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "3593e241c4b8"  # pragma: allowlist secret
down_revision = "12a4acb31f39"  # pragma: allowlist secret
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "userareas",
        sa.Column("gfw_geostore_id", postgresql.UUID(), nullable=False),
        sa.Column("gfw_geojson", sa.TEXT(), nullable=True),
        sa.Column("gfw_area__ha", sa.Numeric(), nullable=True),
        sa.Column("gfw_bbox", postgresql.ARRAY(sa.Numeric()), nullable=True),
        sa.Column(
            "created_on", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_on", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("gfw_geostore_id"),
    )
    op.create_index(
        "userarea_gfw_geostore_id_idx",
        "userareas",
        ["gfw_geostore_id"],
        unique=False,
        postgresql_using="hash",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("userarea_gfw_geostore_id_idx", table_name="userareas")
    op.drop_table("userareas")
    # ### end Alembic commands ###
