"""empty message.

Revision ID: 3e524ef0525f
Revises: 604bf4e66c2b
Create Date: 2024-12-18 00:43:46.681427
"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3e524ef0525f"
down_revision = "604bf4e66c2b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_assets_dataset"), "assets", ["dataset"], unique=False)
    op.create_index(op.f("ix_assets_version"), "assets", ["version"], unique=False)
    op.add_column("dataset_metadata", sa.Column("subtitle", sa.String(), nullable=True))
    op.add_column("version_metadata", sa.Column("subtitle", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("version_metadata", "subtitle")
    op.drop_column("dataset_metadata", "subtitle")
    op.drop_index(op.f("ix_assets_version"), table_name="assets")
    op.drop_index(op.f("ix_assets_dataset"), table_name="assets")
    # ### end Alembic commands ###
