"""Add is_downloadable columns to datasets, versions and assets.

Revision ID: 4763f4b8141a
Revises: d62a9b15f844
Create Date: 2021-07-13 01:10:24.418512
"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4763f4b8141a"  # pragma: allowlist secret
down_revision = "d62a9b15f844"  # pragma: allowlist secret
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("datasets", sa.Column("is_downloadable", sa.Boolean()))
    op.add_column("versions", sa.Column("is_downloadable", sa.Boolean()))
    op.add_column("assets", sa.Column("is_downloadable", sa.Boolean()))
    # ### end Alembic commands ###

    op.execute(
        """UPDATE datasets
                SET is_downloadable = true
                WHERE is_downloadable IS NULL;
        """
    )

    op.execute(
        """UPDATE versions
                SET is_downloadable = true
                WHERE is_downloadable IS NULL;
        """
    )

    op.execute(
        """UPDATE assets
                SET is_downloadable = true
                WHERE is_downloadable IS NULL;
        """
    )
    op.alter_column("datasets", "is_downloadable", nullable=False)
    op.alter_column("versions", "is_downloadable", nullable=False)
    op.alter_column("assets", "is_downloadable", nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("datasets", "is_downloadable")
    op.drop_column("versions", "is_downloadable")
    op.drop_column("assets", "is_downloadable")
    # ### end Alembic commands ###
