"""Have userareas inherit from geostore.

Revision ID: 4a4df534a8f6
Revises: 3593e241c4b8
Create Date: 2020-07-16 13:45:22.996278
"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "4a4df534a8f6"  # pragma: allowlist secret
down_revision = "3593e241c4b8"  # pragma: allowlist secret
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    op.execute("ALTER TABLE userareas INHERIT geostore")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    op.execute("ALTER TABLE userareas NO INHERIT geostore")
