"""empty message.

Revision ID: 537ed623f6df
Revises: cb0c7ea4b3f2
Create Date: 2020-07-12 00:47:16.636779
"""
import geoalchemy2
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "537ed623f6df"  # pragma: allowlist secret
down_revision = "cb0c7ea4b3f2"  # pragma: allowlist secret
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # ### end Alembic commands ###
    op.drop_table("userareas")

    op.drop_column("geostore", "gfw_bbox")

    op.add_column(
        "geostore", sa.Column("gfw_bbox", postgresql.ARRAY(postgresql.NUMERIC))
    )

    op.create_table(
        "userareas",
        sa.Column("gfw_geostore_id", postgresql.UUID(), nullable=False),
        sa.Column("gfw_geojson", sa.String(), nullable=True),
        sa.Column("gfw_area__ha", sa.Numeric(), nullable=True),
        sa.Column("gfw_bbox", postgresql.ARRAY(postgresql.NUMERIC), nullable=True,),
        sa.Column(
            "created_on", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_on", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("gfw_geostore_id"),
    )
    op.create_index(
        "_userarea_gfw_geostore_id_idx",
        "userareas",
        ["gfw_geostore_id"],
        unique=False,
        postgresql_using="hash",
    )

    op.execute("ALTER TABLE userareas INHERIT geostore")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("userareas")

    op.create_table(
        "userareas",
        sa.Column("gfw_geostore_id", postgresql.UUID(), nullable=False),
        sa.Column("gfw_geojson", sa.String(), nullable=True),
        sa.Column("gfw_area__ha", sa.Numeric(), nullable=True),
        sa.Column(
            "gfw_bbox",
            geoalchemy2.types.Geometry(
                geometry_type="POLYGON",
                srid=4326,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column(
            "created_on", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_on", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("gfw_geostore_id"),
    )
    op.create_index(
        "userarea_gfw_geostore_id_idx",
        "userareas",
        ["gfw_geostore_id"],
        unique=False,
        postgresql_using="hash",
    )
    # ### end Alembic commands ###

    op.execute("ALTER TABLE userareas INHERIT geostore")
    # ### end Alembic commands ###
