"""Add content_date_description to version_metadata

Revision ID: 604bf4e66c2b
Revises: ef3392e8e054
Create Date: 2024-10-31 16:52:56.571782

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '604bf4e66c2b'
down_revision = 'ef3392e8e054'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('version_metadata', sa.Column('content_date_description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('version_metadata', 'content_date_description')
    # ### end Alembic commands ###
