"""empty message

Revision ID: 60797f786775
Revises: b266508112c3
Create Date: 2020-06-20 00:26:38.037981

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import ARRAY, JSONB, UUID

# revision identifiers, used by Alembic.
revision = "60797f786775"  # pragma: allowlist secret
down_revision = "b266508112c3"  # pragma: allowlist secret
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""CREATE EXTENSION "uuid-ossp";""")
    op.alter_column(
        "assets",
        "asset_id",
        existing_type=UUID(),
        server_default=sa.text("uuid_generate_v4()"),
    )
    op.alter_column(
        "assets",
        "is_managed",
        existing_type=sa.Boolean(),
        existing_nullable=False,
        server_default=sa.text("true"),
    )
    op.alter_column(
        "assets",
        "is_default",
        existing_type=sa.Boolean(),
        existing_nullable=False,
        server_default=sa.text("false"),
    )
    op.alter_column(
        "assets",
        "status",
        existing_type=sa.VARCHAR(),
        existing_nullable=False,
        server_default=sa.text("'pending'"),
    )
    op.alter_column(
        "assets",
        "creation_options",
        existing_type=JSONB(),
        server_default=sa.text("'{}'"),
    )
    op.alter_column(
        "assets", "metadata", existing_type=JSONB(), server_default=sa.text("'{}'")
    )
    op.alter_column(
        "assets",
        "change_log",
        existing_type=ARRAY(JSONB()),
        server_default=sa.text("array[]::jsonb[]"),
    )

    op.alter_column(
        "versions",
        "is_latest",
        existing_type=sa.Boolean(),
        nullable=False,
        server_default=sa.text("false"),
    )
    op.alter_column(
        "versions",
        "is_mutable",
        existing_type=sa.Boolean(),
        nullable=False,
        server_default=sa.text("false"),
    )
    op.alter_column(
        "versions",
        "status",
        existing_type=sa.VARCHAR(),
        nullable=False,
        server_default=sa.text("'pending'"),
    )
    op.alter_column(
        "versions",
        "has_geostore",
        existing_type=sa.Boolean(),
        nullable=False,
        server_default=sa.text("false"),
    )
    op.alter_column(
        "versions",
        "creation_options",
        existing_type=JSONB(),
        server_default=sa.text("'{}'"),
    )
    op.alter_column(
        "versions", "metadata", existing_type=JSONB(), server_default=sa.text("'{}'")
    )
    op.alter_column(
        "versions",
        "change_log",
        existing_type=ARRAY(JSONB()),
        server_default=sa.text("array[]::jsonb[]"),
    )
    op.alter_column(
        "datasets", "metadata", existing_type=JSONB(), server_default=sa.text("'{}'")
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("assets", "asset_id", existing_type=UUID(), server_default=None)
    op.alter_column(
        "assets",
        "is_managed",
        existing_type=sa.Boolean(),
        existing_nullable=False,
        server_default=None,
    )
    op.alter_column(
        "assets",
        "is_default",
        existing_type=sa.Boolean(),
        existing_nullable=False,
        server_default=None,
    )
    op.alter_column(
        "assets",
        "status",
        existing_type=sa.VARCHAR(),
        existing_nullable=False,
        server_default=None,
    )
    op.alter_column(
        "assets", "creation_options", existing_type=JSONB(), server_default=None
    )
    op.alter_column("assets", "metadata", existing_type=JSONB(), server_default=None)
    op.alter_column(
        "assets", "change_log", existing_type=ARRAY(JSONB()), server_default=None
    )

    op.alter_column(
        "versions",
        "is_latest",
        existing_type=sa.Boolean(),
        nullable=None,
        server_default=None,
    )
    op.alter_column(
        "versions",
        "is_mutable",
        existing_type=sa.Boolean(),
        nullable=None,
        server_default=None,
    )
    op.alter_column(
        "versions",
        "status",
        existing_type=sa.VARCHAR(),
        nullable=None,
        server_default=None,
    )
    op.alter_column(
        "versions",
        "has_geostore",
        existing_type=sa.Boolean(),
        nullable=None,
        server_default=None,
    )
    op.alter_column(
        "versions", "creation_options", existing_type=JSONB(), server_default=None
    )
    op.alter_column("versions", "metadata", existing_type=JSONB(), server_default=None)
    op.alter_column(
        "versions", "change_log", existing_type=ARRAY(JSONB()), server_default=None
    )
    op.alter_column("datasets", "metadata", existing_type=JSONB(), server_default=None)
    op.execute("""DROP EXTENSION "uuid-ossp";""")
    # ### end Alembic commands ###
