"""empty message

Revision ID: 6e56faf9e16f
Revises: 252af4e403c5
Create Date: 2020-06-12 12:03:10.173305

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "6e56faf9e16f"  # pragma: allowlist secret
down_revision = "252af4e403c5"  # pragma: allowlist secret
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
            CREATE OR REPLACE FUNCTION  reset_latest()
        RETURNS trigger LANGUAGE plpgsql AS
        $$
        BEGIN
            IF NEW.is_latest = true THEN
                UPDATE versions
                  SET is_latest = false
                    WHERE versions.dataset = NEW.dataset
                     AND versions.version <> NEW.version;
            END IF;

        RETURN NEW;
        END;
       $$
       """
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        CREATE OR REPLACE FUNCTION  reset_latest()
        RETURNS trigger LANGUAGE plpgsql AS
        $$
        BEGIN
            IF NEW.is_latest = true THEN
                UPDATE versions
                  SET is_latest = false
                    WHERE versions.dataset = NEW.dataset;
            END IF;

        RETURN NEW;
        END;
       $$
        """
    )
    # ### end Alembic commands ###
