"""empty message

Revision ID: 9636dd98993f
Revises: b275927c8c2d
Create Date: 2020-05-15 05:10:42.302824

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "9636dd98993f"
down_revision = "b275927c8c2d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("assets", "is_managed", existing_type=sa.BOOLEAN(), nullable=False)
    op.create_unique_constraint("uq", "assets", ["dataset", "version", "asset_type"])
    op.create_unique_constraint(None, "assets", ["asset_uri"])
    op.add_column("versions", sa.Column("status", sa.String(), nullable=False))
    op.drop_column("versions", "fields")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "versions",
        sa.Column(
            "fields",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("versions", "status")
    op.drop_constraint(None, "assets", type_="unique")
    op.drop_constraint("uq", "assets", type_="unique")
    op.alter_column("assets", "is_managed", existing_type=sa.BOOLEAN(), nullable=True)
    # ### end Alembic commands ###
