"""empty message

Revision ID: 9b86ea12c201
Revises: bb1ed7d0e219
Create Date: 2020-04-29 23:27:30.879287

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "9b86ea12c201"
down_revision = "bb1ed7d0e219"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "assets",
        sa.Column(
            "change_log",
            postgresql.ARRAY(postgresql.JSONB(astext_type=sa.Text())),
            nullable=True,
        ),
    )
    op.add_column(
        "versions",
        sa.Column(
            "change_log",
            postgresql.ARRAY(postgresql.JSONB(astext_type=sa.Text())),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("versions", "change_log")
    op.drop_column("assets", "change_log")
    # ### end Alembic commands ###
