"""empty message.

Revision ID: a3519919b1b6
Revises: db63f11927c2
Create Date: 2020-07-08 01:33:48.295709
"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "a3519919b1b6"  # pragma: allowlist secret
down_revision = "db63f11927c2"  # pragma: allowlist secret
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "assets",
        sa.Column(
            "fields",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'"),
        ),
    )
    op.add_column(
        "assets",
        sa.Column(
            "stats",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
        ),
    )

    op.execute(
        """UPDATE assets
                SET fields = metadata->'fields',
                metadata = metadata - 'fields'

                WHERE metadata ? 'fields';"""
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """UPDATE assets
                SET metadata = metadata || jsonb_build_object('fields', fields);"""
    )

    op.drop_column("assets", "stats")
    op.drop_column("assets", "fields")
    # ### end Alembic commands ###
