"""empty message

Revision ID: a51077c7ffd9
Revises: 3a7dda631399
Create Date: 2020-05-19 20:53:15.918522

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "a51077c7ffd9"  # pragma: allowlist secret
down_revision = "3a7dda631399"  # pragma: allowlist secret
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("assets", "history")
    op.add_column(
        "versions",
        sa.Column(
            "creation_options", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("versions", "creation_options")
    op.add_column(
        "assets",
        sa.Column(
            "history",
            postgresql.ARRAY(postgresql.JSONB(astext_type=sa.Text())),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
