"""empty message.

Revision ID: aa5aefcbdfcf
Revises: 4763f4b8141a
Create Date: 2021-10-12 22:17:29.106137
"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "aa5aefcbdfcf"  # pragma: allowlist secret
down_revision = "a5787f2eefe5"  # pragma: allowlist secret
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "assets",
        sa.Column(
            "revision_history",
            postgresql.ARRAY(postgresql.JSONB(astext_type=sa.Text())),
            nullable=True,
        ),
    )
    op.add_column("assets", sa.Column("latest_revision", sa.String(), nullable=True))
    op.add_column("assets", sa.Column("source_version", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("assets", "source_version")
    op.drop_column("assets", "latest_revision")
    op.drop_column("assets", "revision_history")
    # ### end Alembic commands ###
