"""update resolution metadata fields

Revision ID: ab98e958dc3b
Revises: d767b6dd2c4c
Create Date: 2024-09-10 13:49:58.066058

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ab98e958dc3b'
down_revision = 'd767b6dd2c4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dataset_metadata', 'resolution', nullable=False, new_column_name='spatial_resolution')
    op.add_column('dataset_metadata', sa.Column('resolution_description', sa.String(), nullable=True))
    op.alter_column('version_metadata', 'resolution', nullable=False, new_column_name='spatial_resolution')
    op.add_column('version_metadata', sa.Column('resolution_description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dataset_metadata', 'spatial_resolution', nullable=False, new_column_name='resolution')
    op.drop_column('version_metadata', 'resolution_description')
    op.alter_column('version_metadata', 'spatial_resolution', nullable=False, new_column_name='resolution')
    op.drop_column('dataset_metadata', 'resolution_description')
    # ### end Alembic commands ###
