"""empty message.

Revision ID: b275927c8c2d
Revises: 9b86ea12c201
Create Date: 2020-05-08 15:08:03.988973
"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "b275927c8c2d"  # pragma: allowlist secret
down_revision = "9b86ea12c201"  # pragma: allowlist secret
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "versions",
        sa.Column("fields", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.drop_column("versions", "has_raster_tile_cache")
    op.drop_column("versions", "has_vector_tile_cache")
    op.drop_column("versions", "has_feature_info")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "versions",
        sa.Column("has_feature_info", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "versions",
        sa.Column(
            "has_vector_tile_cache", sa.BOOLEAN(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "versions",
        sa.Column(
            "has_raster_tile_cache", sa.BOOLEAN(), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("versions", "fields")
    # ### end Alembic commands ###
