"""empty message

Revision ID: c1208ae3f96e
Revises: f46eb3aff594
Create Date: 2020-06-24 17:22:42.171055

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import UUID

# revision identifiers, used by Alembic.
revision = "c1208ae3f96e"  # pragma: allowlist secret
down_revision = "f46eb3aff594"  # pragma: allowlist secret
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("tasks", "task_id", type_=UUID(), postgresql_using="task_id::uuid")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tasks", "task_id", type_=sa.String(), postgresql_using="task_id::varchar"
    )
    # ### end Alembic commands ###
