"""Rename api key nick name to alias, add unique constraint.

Revision ID: d62a9b15f844
Revises: bf6a4909ff4d
Create Date: 2021-05-01 01:29:13.157933
"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d62a9b15f844"  # pragma: allowlist secret
down_revision = "bf6a4909ff4d"  # pragma: allowlist secret
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("api_keys", sa.Column("alias", sa.String(), nullable=False))
    op.create_unique_constraint("alias_user_id_uc", "api_keys", ["alias", "user_id"])
    op.drop_column("api_keys", "nick_name")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "api_keys",
        sa.Column("nick_name", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_constraint("alias_user_id_uc", "api_keys", type_="unique")
    op.drop_column("api_keys", "alias")
    # ### end Alembic commands ###
