"""empty message.

Revision ID: d767b6dd2c4c
Revises: 04fcb4f2408a
Create Date: 2024-04-25 19:38:35.223004
"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d767b6dd2c4c"
down_revision = "04fcb4f2408a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("datasets", sa.Column("owner_id", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("datasets", "owner_id")
    # ### end Alembic commands ###
