"""empty message

Revision ID: d846d15cc93c
Revises: 15a427d4fa82
Create Date: 2020-05-22 02:33:34.075680

"""

# revision identifiers, used by Alembic.
revision = "d846d15cc93c"  # pragma: allowlist secret
down_revision = "15a427d4fa82"  # pragma: allowlist secret
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
