"""empty message.

Revision ID: db63f11927c2
Revises: b3baf70b4a4b
Create Date: 2020-07-03 16:35:30.920417
"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "db63f11927c2"  # pragma: allowlist secret
down_revision = "b3baf70b4a4b"  # pragma: allowlist secret
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # rename metadata key fields_ to fields
    op.execute(
        """UPDATE assets
                SET metadata = metadata - 'fields_' || jsonb_build_object('fields', metadata->'fields_')
                WHERE metadata ? 'fields_';"""
    )

    # rename keys inside fields from field_name_ to field_name
    op.execute(
        """UPDATE assets
                SET metadata = jsonb_set(metadata, '{fields}', REPLACE((metadata->'fields')::text, 'field_name_', 'field_name')::jsonb, false)
                WHERE metadata ? 'fields';"""
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute(
        """UPDATE assets
                SET metadata = jsonb_set(metadata, '{fields}', REPLACE((metadata->'fields')::text, 'field_name', 'field_name_')::jsonb, false)
                WHERE metadata ? 'fields';"""
    )

    op.execute(
        """UPDATE assets
                SET metadata = metadata - 'fields' || jsonb_build_object('fields_', metadata->'fields')
                WHERE metadata ? 'fields';"""
    )

    # ### end Alembic commands ###
