"""empty message

Revision ID: e8a7dc28a874
Revises: d767b6dd2c4c
Create Date: 2024-09-06 20:37:11.512231

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e8a7dc28a874'
down_revision = 'd767b6dd2c4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset_metadata', sa.Column('spatial_resolution', sa.Numeric(), nullable=True))
    op.add_column('dataset_metadata', sa.Column('resolution_description', sa.String(), nullable=True))
    op.drop_column('dataset_metadata', 'resolution')
    op.add_column('version_metadata', sa.Column('spatial_resolution', sa.Numeric(), nullable=True))
    op.add_column('version_metadata', sa.Column('resolution_description', sa.String(), nullable=True))
    op.drop_column('version_metadata', 'resolution')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('version_metadata', sa.Column('resolution', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.drop_column('version_metadata', 'resolution_description')
    op.drop_column('version_metadata', 'spatial_resolution')
    op.add_column('dataset_metadata', sa.Column('resolution', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.drop_column('dataset_metadata', 'resolution_description')
    op.drop_column('dataset_metadata', 'spatial_resolution')
    # ### end Alembic commands ###
