"""update resolution metadata fields

Revision ID: ef3392e8e054
Revises: d767b6dd2c4c
Create Date: 2024-09-10 14:19:43.424752

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ef3392e8e054'
down_revision = 'd767b6dd2c4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dataset_metadata', 'resolution', nullable=True, new_column_name='spatial_resolution')
    op.add_column('dataset_metadata', sa.Column('resolution_description', sa.String(), nullable=True))
    op.alter_column('version_metadata', 'resolution', nullable=True, new_column_name='spatial_resolution')
    op.add_column('version_metadata', sa.Column('resolution_description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dataset_metadata', 'spatial_resolution', nullable=True, new_column_name='resolution')
    op.drop_column('version_metadata', 'resolution_description')
    op.alter_column('version_metadata', 'spatial_resolution', nullable=True, new_column_name='resolution')
    op.drop_column('dataset_metadata', 'resolution_description')
    # ### end Alembic commands ###
