"""empty message

Revision ID: f46eb3aff594
Revises: 6e56faf9e16f
Create Date: 2020-06-13 01:38:20.446751

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "f46eb3aff594"
down_revision = "6e56faf9e16f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands added manually to adjust PK on assets table ###
    op.drop_constraint("assets_pkey", "assets", type_="primary")
    op.create_primary_key("assets_pkey", "assets", ["asset_id",])

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tasks",
        sa.Column(
            "created_on", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_on", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("task_id", sa.String(), nullable=False),
        sa.Column("asset_id", postgresql.UUID(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column(
            "change_log",
            postgresql.ARRAY(postgresql.JSONB(astext_type=sa.Text())),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["asset_id"], ["assets.asset_id"], name="fk"),
        sa.PrimaryKeyConstraint("task_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tasks")
    # ### end Alembic commands ###

    # ### commands added manually to adjust PK on assets table ###
    op.drop_constraint("assets_pkey", "assets", type_="primary")
    op.create_primary_key("assets_pkey", "assets", ["dataset", "version", "asset_type"])
