#!/bin/bash

set -e


# allow to overwrite GIT_SHA
POSITIONAL=()
GIT_SHA=$(git rev-parse HEAD)
while [[ $# -gt 0 ]]
do
key="$1"

case $key in
    -g|--git_sha)
    GIT_SHA="$2"
    shift # past argument
    shift # past value
    ;;
    *)    # unknown option
    POSITIONAL+=("$1") # save it in an array for later
    shift # past argument
    ;;
esac
done
set -- "${POSITIONAL[@]}" # restore positional parameters

docker-compose -f terraform/docker/docker-compose.yml build
docker-compose -f terraform/docker/docker-compose.yml run --entrypoint delete_workspace --rm  terraform "$@" -var="git_sha=${GIT_SHA}"