#!/bin/bash

set -e

docker build -t batch_gdal-python_test . -f batch/gdal-python.dockerfile
docker build -t batch_postgresql-client_test . -f batch/postgresql-client.dockerfile
docker build -t batch_tile_cache_test . -f batch/tile_cache.dockerfile
docker-compose -f docker-compose.dev.yml up --abort-on-container-exit --remove-orphans --build
