#!/bin/bash

set -e


# Default values
POSITIONAL=()
BUILD=true
DO_COV=
DISABLE_WARNINGS="--disable-warnings"
SHOW_STDOUT=
# extracting cmd line arguments
while [[ $# -gt 0 ]]
do
  key="$1"

  case $key in
      --no_build)
      BUILD=false
      shift # past argument
      ;;
      --without-hanging-tests)
      HANGING=--without-hanging-tests
      shift # past argument
      ;;
      --with-slow-tests)
      SLOW=--with-slow-tests
      shift # past argument
      ;;
      --do-cov)
      DO_COV=--cov=app
      shift # past argument
      ;;
      --show-warnings)
      DISABLE_WARNINGS=
      shift # past argument
      ;;
      --show-stdout)
      SHOW_STDOUT=--capture=no
      shift # past argument
      ;;
      --moto-port=*)
      # prevent port binding issues by explicitly setting the motoserver s3 port
      # https://developer.apple.com/forums/thread/682332
      export MOTO_PORT="${key#*=}"
      shift # past argument=value
      ;;
      *)    # unknown option
      POSITIONAL+=("$1") # save it in an array for later
      shift # past argument
      ;;
  esac
done
set -- "${POSITIONAL[@]}" # restore positional parameters

# If no tests specified, do whole tests directory
args=$*
if [ $# -eq 0 ]; then
   args=tests
fi

if [ "${BUILD}" = true ]; then
  docker build -t universal_batch_test . -f batch/universal_batch.dockerfile
#  docker build -t batch_gdal-python_test . -f batch/gdal-python.dockerfile
#  docker build -t batch_postgresql-client_test . -f batch/postgresql-client.dockerfile
#  docker build -t batch_tile_cache_test . -f batch/tile_cache.dockerfile
  docker build -t pixetl_test . -f batch/pixetl.dockerfile
  docker-compose -f docker-compose.test.yml --project-name gfw-data-api_test build --no-cache app_test
fi

set +e

# Everything from "--cov-report on" become the arguments to the pytest run inside the docker.
docker-compose -f docker-compose.test.yml --project-name gfw-data-api_test run --rm --name app_test app_test --cov-report xml:/app/tests/cobertura.xml $HANGING $SLOW  $DO_COV $DISABLE_WARNINGS $SHOW_STDOUT $args
exit_code=$?
docker-compose -f docker-compose.test.yml --project-name gfw-data-api_test down --remove-orphans
exit $exit_code
