environment                    = "dev"
log_level                      = "debug"
service_url                    = "https://dev-data-api.globalforestwatch.org" # fake, needed for CloudFront
rw_api_url                     = "https://api.resourcewatch.org"
desired_count                  = 1
auto_scaling_min_capacity      = 1
auto_scaling_max_capacity      = 5
lambda_analysis_workspace      = "feature-otf_lists"
key_pair                       = "dmannarino_gfw"
create_cloudfront_distribution = false
new_relic_license_key_arn      = "arn:aws:secretsmanager:us-east-1:563860007740:secret:newrelic/license_key-lolw24"
load_balancer_security_group   = "sg-07c9331c01f8da1c8"
load_balancer_arn              = "arn:aws:elasticloadbalancing:us-east-1:563860007740:loadbalancer/app/gfw-data-api-elb-shared-dev-lb/60c3ad42ca6522e3"
lb_dns_name                    = "gfw-data-api-elb-shared-dev-lb-10091095.us-east-1.elb.amazonaws.com"
# api_gateway_id        = "ett3a69n8h"
# api_gw_external_up_id = "08ipvv"
# api_gw_internal_up_id = "ahj8m0"
# api_gateway_url       = "https://ett3a69n8h.execute-api.us-east-1.amazonaws.com/deploy"
